# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'movie_rating',
                'managed': False,
            },
        ),
    ]
