# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_cinema_info_movie_resource_price_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCollect',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(primary_key=True)),
            ],
            options={
                'db_table': 'movie_ucollect',
                'managed': False,
            },
        ),
    ]
